### ISSUE TITLE
overlapping with old panel

### ISSUE THREAD

**Issue by SelfReflection31** [paul-merkamp/LCBetterSaves#13]
![image](https://github.com/paul-merkamp/LCBetterSaves/assets/113463662/bdb816b4-bea2-48b2-babf-3e4a16f0bf92)

now idk if this is related 
![image](https://github.com/paul-merkamp/LCBetterSaves/assets/113463662/d92912f7-d70e-4791-ad38-33fafae654db)

this happens on the latest and vanilla lethal company(only this mod installed) for me.

**Comment by RKirkpatrick** [comment]
I noticed this started happening after updating from version 1.4 to version 1.5 of the mod. I decided to check today if anyone else has reported this issue.

I deleted my old saves to try to recreate the issue on version 1.6.1. The issue is gone for me until I save the game with the late game upgrades (lgu) mod installed. It also looks like late game upgrades support was added in version 1.5 of the mod.

Before saving with lgu :
![image](https://github.com/paul-merkamp/LCBetterSaves/assets/39039840/8cbf962e-3d03-40a3-933c-26e152c41a96)

After saving with lgu :
![image](https://github.com/paul-merkamp/LCBetterSaves/assets/39039840/8971c9f1-5a51-4a78-840c-e4a1527342cf)

I did a little more testing. This mod creates LGU_1.json when saving with the lgu mod installed with a different number for each save. Deleting the .json file fixes the UI issue but deletes lgu progression. Deleting the save from the ingame menu doesn't delete the .json file. 

If you have ever saved with this mod and lgu installed there are probably some .json files in your saves folder that are causing this issue when only LCBetterSaves is installed. Deleting the json file would only temporarliy fix the issue if you're still using the lgu mod.
![image](https://github.com/paul-merkamp/LCBetterSaves/assets/39039840/dbf884a3-aca5-4154-8be0-b8ceeee22764)

**Comment by aroudntehwolrd** [comment]
I've deleted the IntroLGU file, and yet this problem still persists. Worse yet, I can't create new saves, or at least I am unable to see or select them after they've been made. I've tried many things, and none have worked. Even just loading this mod by itself and no other, this problem is still present, for both v45 and v47.
Looking at the logs, it says:

> Error occurred while refreshing save buttons: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
