### ISSUE TITLE
Suggestion: New saves should be automatically renamed

### ISSUE THREAD

**Issue by tornado-ii** [paul-merkamp/LCBetterSaves#21]
When creating a new file, the default name is always going to be "Save X" (where 'X' is the number of saves). The game will always load into the ship after creating a save, which doesn't allow you to rename the save before starting. If you are setting up a test save or a save with mods different from previous saves, you have to exit the game to the main menu just to rename it appropriately.
I believe that new saves should automatically inherit the server name, just as saves being renamed do. This way, instead of creating LCSaveFile5 with name "Save 5", it would create LCSaveFile5 with name "Example".

**Comment by paul-merkamp** [comment]
Since the server name field is already multipurpose, I'd be worried that this change in behavior would confuse existing users of the mod or make the overall LCBetterSaves experience more clunky.

Instead, my preferred approach would be creating a save file happening separately from loading a save file. This way you can name it right after you create it, and **then** load it up.

I'm unsure how much work this'll take, but I'll plan it as a feature. Not exactly sure when I will have the time to implement it.
