### ISSUE TITLE
Question about Restoring

### ISSUE THREAD

**Issue by on4r4p** [paul-merkamp/LCBetterSaves#5]
Does you mod is able to restore a save ?
Like iv made a great run with one save and died at the end ,
am i able to restore it to the previous state?

**Comment by paul-merkamp** [comment]
I have had a couple of people reach out about this, but unfortunately this is outside the scope of the mod.

Mostly because a lot of (most?) saves that would be worth saving are already screwed at the point that I'd be creating the backup.

To my knowledge, there isn't a way to recover lost saves. What I'd recommend is closing the game before you get fired, then using this tool to edit your save so you have more time:
https://github.com/lawrencea13/LethalCompanySaveManager/releases/tag/Stable
